export default [
   {recording:"/images/login-pic.jpg",
    title: "Annual meeting",
    views: "42",
    size:"30",
    last_modified:"02/05/2021"},
   {recording:"/images/login-pic.jpg",
    title: "Crew walkthrough",
    views: "80",
    size:"10",
    last_modified:"02/06/2021"},
   {recording:"/images/login-pic.jpg",
    title: "Skill Acquisition",
    views: "59",
    size:"98",
    last_modified:"02/05/2022"},
   {recording:"/images/login-pic.jpg",
    title:"Zoom meeting headlines",
    views: "308",
    size:"123",
    last_modified:"05/01/2021"},
   {recording:"/images/login-pic.jpg",
    title:"New Proposal",
    views: "1000",
    size:"84",
    last_modified:"09/06/2021"},
   {recording:"/images/login-pic.jpg",
    title: "Latest Project Ideas",
    views: "5000",
    size:"94",
    last_modified:"07/08/2021"},
]